### ISSUE TITLE
Docker 入门

### ISSUE THREAD

**Issue by iugo** [zsqk/zsqk#101]
# Docker 入门

- 有几个概念, image, container.
- 一般开发人员维护 image, 运维人员维护 container.
- 在 container 执行一个命令后, 如果该命令退出, 则 container 就会退出, 如果命令一直运行着, 则 container 不退出.
- docker 与 daemon 是相斥的. 或者说, docker 是 daemon 的一种实现方法.
- 在一个 docker container 内, 应该只有一个主应用.

## 适用版本

Docker version 1.12.3, build 6b644ec

当时的版本比较低, 现在 docker 已经按照年月来安排版本号了.

版本号在 18.09.

## 查看 docker 镜像列表

```
docker images
```

https://docs.docker.com/engine/reference/commandline/images/

## 移除 docker 镜像

```bash
docker rmi ${IMAGE ID}

# 移除所有镜像
docker rmi $(docker images -a -q)
```

## 查看正在运行中的 docker 容器

```bash
# 旧命令 https://docs.docker.com/engine/reference/commandline/ps/
docker ps

# 新命令 https://docs.docker.com/engine/reference/commandline/container_ls/
docker container ls
```

https://stackoverflow.com/questions/16840409/how-to-list-containers-in-docker

## 获取 docker 容器日志

```
docker container logs ${CONTAINER ID}
```

## 在 docker 容器中运行另外的命令

```
docker container exec ${CONTAINER ID} ${COMMAND}
```

## 进入 docker 容器内部

!!! 尽量不要使用该方法, 而是使用 logs 或 exec 来替代.

```
docker attach ${CONTAINER ID}
```

control + d 会停止该容器.
文档说 control + c 会向容器发送关闭信号, 我实测 control + d 会运行 `exit` 命令来关闭.

如果要离开而不停止容器, 需要 control + p + q.

参考: https://stackoverflow.com/questions/19688314/how-do-you-attach-and-detach-from-dockers-process
文档: https://docs.docker.com/engine/reference/commandline/attach/#extended-description

## 运行/停止一个容器

```
docker start ${CONTAINER ID}
docker stop ${CONTAINER ID}
```

https://docs.docker.com/engine/reference/commandline/start/

## 常用参数

```bash
# 过滤 https://docs.docker.com/engine/reference/commandline/ps/#filtering
--filter , -f

# 仅获取 ID
--quiet , -q
```

## 写 Dockerfile 文件

https://docs.docker.com/develop/develop-images/dockerfile_best-practices

**Comment by iugo** [comment]
练习: https://labs.play-with-docker.com/

postgre 练习: https://labs.play-with-docker.com/?stack=https://raw.githubusercontent.com/docker-library/docs/9efeec18b6b2ed232cf0fbd3914b6211e16e242c/postgres/stack.yml

临时访问地址规则及举例:

http://ip172-18-0-20-bm80jtef578g00b3n2a0-8080.direct.labs.play-with-docker.com/

- IP
- ID
- Port

入门: https://training.play-with-docker.com/beginner-linux/

> "Interactive containers are useful when you are putting together your own image. You can run a container and verify all the steps you need to deploy your app, and capture them in a Dockerfile."

我想知道这句话中具体的技巧.

**Comment by iugo** [comment]
编排

docker stack

支持两种编排方案:

Swarm, Kubernetes

Swarm 示例:

```yaml
# https://raw.githubusercontent.com/docker-library/docs/9efeec18b6b2ed232cf0fbd3914b6211e16e242c/postgres/stack.yml
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
```

编排时的网络协同:

使用 overlay network 解决协同问题
https://docs.docker.com/network/overlay/

links 参数是过时的, 可以使用
https://forums.docker.com/t/docker-swarm-with-compose-file-does-not-recognize-links/42356
