### ISSUE TITLE
也许我不需要 Sass, Less -- CSS variables 就能解决大多数问题

### ISSUE THREAD

**Issue by iugo** [zsqk/zsqk#112]
相关文档: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

核心语法:

```css
.page {
  --color-black: #222222;
  color: var(--color-black);
}
```

以 `--` 作为变量前缀, 以 `var()` 使用变量.
